---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::277310647XXX:role/prd-eks-useast1-core-alb-role


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: core-deployment-service-account
  namespace: prd-eks-useast1
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::277310647XXX:role/prd-eks-useast1-core-secrets